### ISSUE TITLE
Unit tests fail on Windows

### ISSUE THREAD

**Issue by adamcin** [adamcin/oakpal#20]
```[ERROR] Tests run: 7, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.061 s <<< FAILURE! - in net.adamcin.oakpal.testing.TestPackageUtilTest

[ERROR] testPrepareTestPackageFromFolder(net.adamcin.oakpal.testing.TestPackageUtilTest)  Time elapsed: 0.015 s  <<< FAILURE!

java.lang.AssertionError: entryName must not begin with a slash: /jcr_root/

	at net.adamcin.oakpal.testing.TestPackageUtilTest.testPrepareTestPackageFromFolder(TestPackageUtilTest.java:69)

[ERROR] testBuildJarFromDir(net.adamcin.oakpal.testing.TestPackageUtilTest)  Time elapsed: 0.012 s  <<< FAILURE!

java.lang.AssertionError: embedded jar has entries expected:<[someScript.js, META-INF/, META-INF/MANIFEST.MF]> but was:<[META-INF/MANIFEST.MF, /META-INF/, /someScript.js]>

	at net.adamcin.oakpal.testing.TestPackageUtilTest.testBuildJarFromDir(TestPackageUtilTest.java:136)```

**Comment by adamcin** [comment]
resolved with 3d1044c2d .
