### ISSUE TITLE
Line too long exception when validating package

### ISSUE THREAD

**Issue by pun-ky** [adamcin/oakpal#45]
```
com.cognifide.gradle.aem.common.pkg.PackageValidator.perform(PackageValidator.kt:86)
        at com.cognifide.gradle.aem.pkg.tasks.PackageCompose.copy(PackageCompose.kt:175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        ... 97 more
Caused by: net.adamcin.oakpal.core.Fun$FunRuntimeException: java.io.IOException: line too long
        at net.adamcin.oakpal.core.Fun.lambda$uncheckVoid1$39(Fun.java:1189)
        at java.util.Optional.ifPresent(Optional.java:159)
        at net.adamcin.oakpal.core.OakMachine.processPackage(OakMachine.java:671)
        at net.adamcin.oakpal.core.OakMachine.processUploadedPackage(OakMachine.java:785)
        at net.adamcin.oakpal.core.OakMachine.processPackageFile(OakMachine.java:819)
        ... 130 more
Caused by: java.io.IOException: line too long
        at java.util.jar.Attributes.read(Attributes.java:379)
        at java.util.jar.Manifest.read(Manifest.java:234)
        at java.util.jar.JarInputStream.checkManifest(JarInputStream.java:95)
        at java.util.jar.JarInputStream.<init>(JarInputStream.java:86)
        at java.util.jar.JarInputStream.<init>(JarInputStream.java:62)
        at net.adamcin.oakpal.core.OakMachine.lambda$processPackage$3(OakMachine.java:674)
        at net.adamcin.oakpal.core.Fun.lambda$uncheckVoid1$39(Fun.java:1187)
        ... 134 more
```

I don't know details right now, how it happened , but letting know that here sth smells bad.
I will try to figure out that jar manfest, how it was looking at that moment

@adamcin any thoughts, what could be a cause?

**Comment by adamcin** [comment]
@pun-ky I do know that line length is a constraint for the official Manifest construction. Can you paste the package's MANIFEST.MF here?

**Comment by pun-ky** [comment]
Yes sure. But I am ooo. Back on Monday 😉

**Comment by pun-ky** [comment]
Still when we skipped validation package was successfully installed.

BTW why package validation is checking bundles / jars? Maybe aQute bnd Jar class (from other package) need be used instead

**Comment by dprzybyl** [comment]
I also have the same issue, here [MANIFEST.MF](https://github.com/adamcin/oakpal/files/3915504/MANIFEST.MF.LOG) file, I hope it helps

**Comment by pun-ky** [comment]
seems that `Content-Package-Roots` are generated by GAP package plugin and that value need to be splitted to avoid reaching max line length.

**Comment by adamcin** [comment]
I think I need to parse a manifest through an internal method in order to do so leniently.

**Comment by pun-ky** [comment]
From gap side i am generating this file by my own / not by any exiting class which is handling line wrapping correctly. I think that I need to do so rather than you parsing it in different way.

**Comment by pun-ky** [comment]
the cause was GAP itself generating this manifest. closing, unrelated.
