### ISSUE TITLE
Problems with newer dependencies

### ISSUE THREAD

**Issue by badvision** [adamcin/oakpal#7]
I have an updated branch of ACS Commons with newer dependencies and am unable to run the oakpal checks now without lots of errors.  Branch can be found here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1704#

```
--- oakpal-maven-plugin:1.1.13:scan (oakpal-scan) @ acs-aem-commons-content ---
Found a new index node [reference]. Reindexing is requested
Reindexing will be performed for following indexes: [/oak:index/uuid, /oak:index/reference, /oak:index/nodetype]
Indexing report
    - /oak:index/uuid*(0)
    - /oak:index/reference*(0)
    - /oak:index/nodetype*(1254)

Reindexing completed
Reindexing will be performed for following indexes: [/oak:index/principalName, /oak:index/authorizableId, /oak:index/acPrincipalName, /oak:index/repMembers]
Indexing report
    - /oak:index/principalName*(2)
    - /oak:index/authorizableId*(2)
    - /oak:index/acPrincipalName*(0)
    - /oak:index/repMembers*(0)

Reindexing completed
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 0/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 1/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 2/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 3/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 4/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 5/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 6/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 7/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 8/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Retrying import from checkpoint at /etc/acs-commons/lists/font-awesome-icons. Retries 9/10
Error during processing of /home/users/system/acs-commons: javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system
E /home/users/system/acs-commons (javax.jcr.nodetype.ConstraintViolationException: No matching node definition found for system)
E /home/users/system/acs-commons/automatic-package-replicator (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/bulk-workflow (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/component-error-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/dispatcher-flush-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/email-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-oak-index-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/ensure-service-user (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/error-page-handler (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/form-helper-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/httpcache-jcr-storage-provider (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/manage-controlled-processes (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/on-deploy-scripts-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/package-replication-event-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/review-task-asset-mover-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/shared-component-props-service (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/system-notifications (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/twitter-updater (java.lang.IllegalStateException: Parent node not found.)
E /home/users/system/acs-commons/workflow-remover (java.lang.IllegalStateException: Parent node not found.)
error during auto save - retrying after refresh...
Error while committing changes. Aborting.
Error during install.
javax.jcr.nodetype.ConstraintViolationException: OakConstraint0025: /home/users[[rep:AuthorizableFolder, rep:AccessControllable]]: Unexpected child node system found in a new node
	at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:225)
	at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:212)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.newRepositoryException(SessionDelegate.java:670)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:496)
	at org.apache.jackrabbit.oak.jcr.session.SessionImpl$8.performVoid(SessionImpl.java:420)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:274)
	at org.apache.jackrabbit.oak.jcr.session.SessionImpl.save(SessionImpl.java:417)
	at org.apache.jackrabbit.vault.fs.io.AutoSave.save(AutoSave.java:177)
	at org.apache.jackrabbit.vault.fs.io.Importer.run(Importer.java:430)
	at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:233)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:400)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:359)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:345)
	at net.adamcin.oakpal.core.OakMachine.processPackage(OakMachine.java:428)
	at net.adamcin.oakpal.core.OakMachine.processPackageFile(OakMachine.java:486)
	at net.adamcin.oakpal.core.OakMachine.scanPackages(OakMachine.java:329)
	at net.adamcin.oakpal.core.OakMachine.scanPackage(OakMachine.java:270)
	at net.adamcin.oakpal.maven.mojo.ScanArtifactMojo.executeGuardedIntegrationTest(ScanArtifactMojo.java:64)
	at net.adamcin.oakpal.maven.mojo.AbstractMojo.execute(AbstractMojo.java:241)
	at net.adamcin.oakpal.maven.mojo.ScanArtifactMojo.execute(ScanArtifactMojo.java:41)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.jackrabbit.oak.api.CommitFailedException: OakConstraint0025: /home/users[[rep:AuthorizableFolder, rep:AccessControllable]]: Unexpected child node system found in a new node
	at org.apache.jackrabbit.oak.plugins.nodetype.TypeEditor$1.onConstraintViolation(TypeEditor.java:109)
	at org.apache.jackrabbit.oak.plugins.nodetype.TypeEditor.constraintViolation(TypeEditor.java:229)
	at org.apache.jackrabbit.oak.plugins.nodetype.TypeEditor.checkNodeTypeConstraints(TypeEditor.java:479)
	at org.apache.jackrabbit.oak.plugins.nodetype.TypeEditor.enter(TypeEditor.java:271)
	at org.apache.jackrabbit.oak.spi.commit.VisibleEditor.enter(VisibleEditor.java:54)
	at org.apache.jackrabbit.oak.spi.commit.CompositeEditor.enter(CompositeEditor.java:66)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:145)
	at org.apache.jackrabbit.oak.plugins.memory.MemoryNodeState.compareAgainstBaseState(MemoryNodeState.java:162)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
	at org.apache.jackrabbit.oak.plugins.memory.MemoryNodeState.compareAgainstBaseState(MemoryNodeState.java:162)
	at org.apache.jackrabbit.oak.spi.commit.EditorDiff.process(EditorDiff.java:52)
	at org.apache.jackrabbit.oak.spi.commit.EditorHook.processCommit(EditorHook.java:55)
	at org.apache.jackrabbit.oak.spi.commit.CompositeHook.processCommit(CompositeHook.java:61)
	at org.apache.jackrabbit.oak.spi.commit.CompositeHook.processCommit(CompositeHook.java:61)
	at org.apache.jackrabbit.oak.plugins.memory.MemoryNodeStore$MemoryNodeStoreBranch.merge(MemoryNodeStore.java:295)
	at org.apache.jackrabbit.oak.plugins.memory.MemoryNodeStore.merge(MemoryNodeStore.java:134)
	at org.apache.jackrabbit.oak.core.MutableRoot.commit(MutableRoot.java:250)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.commit(SessionDelegate.java:347)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:494)
	... 38 more
```

**Comment by adamcin** [comment]
Okay, I'll take a look this weekend.

**Comment by adamcin** [comment]
@badvision I narrowed it down to the content-package-maven-plugin, if you can believe it. In 0.5.24, it doesn't include some important .content.xml files, presumably because they aren't covered by the workspace filter. 

0.0.24:

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/524972/51443256-e3914300-1c9a-11e9-8d68-b0d6dc5eac09.png">

0.5.24:

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/524972/51443263-07548900-1c9b-11e9-847c-8e94838d890c.png">

The important thing here is that the parent node definitions are necessary because they declare nodetypes other than nt:folder, which basically doesn't allow anything useful, and in this case, we need to establish a hierarchy of rep:AuthorizableFolder nodes under /home/users and /home/groups in order to validate the authorizable nodes installed by the acs-commons package.

I'll need to evaluate the behavior of newer content-package-maven-plugin and filevault-package-maven-plugin versions to see if this was a permanent choice or not.

**Comment by adamcin** [comment]
@badvision oakpal version 1.2.0-SNAPSHOT should also solve this by pre-creating the user and group home directories
